Repository geisweiller/global-components, pull requests merged in 2024-01, with the labels that each got.

#1 feat(vitest): setup tests and clean up
  package.json
  setupTests.ts
  src/components/button/Button.test.tsx
  src/components/button/Button.tsx
  src/components/button/button.css
  src/components/header/Header.stories.ts
  src/components/header/Header.tsx
  src/components/header/header.css
  src/components/page/Page.stories.ts
  src/components/page/Page.tsx
  src/components/page/page.css
  tsconfig.json
  vite.config.ts
  vitest.config.ts
  yarn.lock
Labels: enhancement

#2 chore(github): add github actions
  .github/workflows/ci.yml
  src/components/button/Button.tsx
Labels: enhancement

#3 chore(script): generate component script
  package.json
  scripts/generate-component/component-template.js
  scripts/generate-component/index.js
Labels: enhancement

#4 chore(pull-request): create pull_request_template.md
  .storybook/.github/pull_request_template.md
Labels: enhancement

#5 cleanup(src/root)
  index.html
  public/vite.svg
  src/App.css
  src/App.tsx
  src/index.css
  src/main.tsx
  yarn.lock
Labels: enhancement

#7 fix(scripts): fix component script
  scripts/generate-component/component-template.js
  scripts/generate-component/index.js
Labels: bug, enhancement

#9 fix(github): fix pr template
  .github/pull_request_template.md
Labels: bug

#10 counter(components): create counter component without styles yet
  .storybook/preview.ts
  package.json
  postcss.config.js
  scripts/generate-component/component-template.js
  src/components/counter/counter.stories.ts
  src/components/counter/counter.test.tsx
  src/components/counter/counter.tsx
  src/main.tsx
  tailwind.config.js
Labels: enhancement

#11 feat(components): text component
  package.json
  src/components/text/text.stories.ts
  src/components/text/text.test.tsx
  src/components/text/text.tsx
  src/index.ts
  src/utils/class-names.ts
Labels: enhancement
